version: '3'
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=pandemonium'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=shCGJoH0P0oS6elqS'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
